### ISSUE TITLE
Incorrect Group ID assigned by featurecounts_deseq2.r

### ISSUE THREAD

**Issue by ikeller** [nf-core/atacseq#102]
featurecounts_deseq2.r expects that sample names end in "\_R1" etc and will trim the last 3 characters of the sample name to obtain the group ID for DESeq2. This will not work when there are 10 or more replicates per group. In this case, you end up with twice the expected number of experimental groups, because the underscore is retained in some replicates, for example: Tissue1 and Tissue1_. It would be safer to remove everything starting at the underscore.

**Comment by drpatelh** [comment]
Yes, this is a bug @ikeller 👍 I could swear I fixed this already but I obviously havent!

https://github.com/nf-core/atacseq/blob/818c8dcbdac9cc275ad2b7b522b43dcb1fb6201b/bin/featurecounts_deseq2.r#L81

The easiest solution would be to split on `_` and then join everything back to together except the last item.

**Comment by ikeller** [comment]
Thanks for your quick reply. 

I haven't spotted any other issues caused by the 2-digit replicate numbers.

**Comment by drpatelh** [comment]
No worries 👍 Ill try and fix this in the next release which will hopefully be in a couple of weeks.

**Comment by drpatelh** [comment]
Fixed here @ikeller https://github.com/nf-core/atacseq/pull/103/files#diff-14aa6af59da16aa8ac3bc0d442d2c700 so will be sorted in the next release.
