### ISSUE TITLE
Add -T "." option to sort commands

### ISSUE THREAD

**Issue by lconde-ucl** [nf-core/atacseq#111]
Hi,

we are running the ataqseq pipeline and keeps failing at the MergedLibBigWig step with `sort: cannot create temporary file in '/tmpdir/job/3854830.undefined': No such file or directory` errors. 

I believe this is related to https://github.com/nf-core/chipseq/issues/132

Is it possible to implement the suggested solution (add -T "." to the sort commands) in the next release of the pipeline?

Thanks
Lucia

**Comment by drpatelh** [comment]
Hi @lconde-ucl ! Hope you and loved ones are doing well. I have already added [this fix](https://github.com/nf-core/atacseq/pull/72/files) to the pipeline and so will be sorted in the next release. Sorry, been preoccupied with COVID-19 stuff but I will eventually get around to releasing this pipeline 🙂 

Running `export TMPDIR=/tmp/` before the pipeline command should fix the issue for now.

**Comment by lconde-ucl** [comment]
Brilliant thanks! XX
