### ISSUE TITLE
Misleading error message (minor comment)

### ISSUE THREAD

**Issue by ktrns** [nf-core/atacseq#126]
Hi there, 

This is a very minor comment. I was using the parameters `--genome mm10 --igenomes_ignore` and defined the `mm10` files in our config. 

Turns out, I haven't defined `mm10` yet. The error message is: 
```
The provided genome 'mm10' is not available in the iGenomes file. Currently the available genomes are mm9, hg38, MN908947.3
```

You could change "in the iGenomes file" to "in your config file", or anything like that. Or skip it, and just say it is missing. 

Best and thanks a lot for all Nfcore work! 
Katrin

**Comment by drpatelh** [comment]
Hi @ktrns I have fixed this in the rnaseq pipeline https://github.com/nf-core/rnaseq/pull/502/commits/a84b4c88462d566f937a7db6e40fcf19b2853dcc. The plan is to copy these changes to the nf-core pipeline template and then out to each pipeline via the automated sync. The DSL2 version of this pipeline will also have these changes eventually. Hope that is a satisfactory fix. Well spotted BTW 👍
