### ISSUE TITLE
how does MACS2 define a peak in ATACseq analysis using as a default

### ISSUE THREAD

**Issue by elffairy90** [nf-core/atacseq#132]
Hi, 

Just wondering how does MACS2 define a peak in ATACseq analysis using as a default? 

Best regards, 
Jenny

**Comment by drpatelh** [comment]
Hi @elffairy90. The command used to run MACS2 in  the pipeline is [here](https://github.com/nf-core/atacseq/blob/1b3a832db5a53c92c2c89a4d6d79455e860461ad/main.nf#L1145-L1155). The exact parameters passed to this command will depend on user-provided pipeline parameters and whether the data is single-end / paired-end. I believe that answers your question.
