### ISSUE TITLE
Channel used twice as an input

### ISSUE THREAD

**Issue by chbk** [nf-core/atacseq#137]
Bug report for this error:

```
Channel `ch_gene_bed` has been used twice as an input
by process `MERGED_LIB_PLOTPROFILE` and process `MAKE_TSS_BED`

 -- Check script 'nf-core/atacseq/main.nf' at line: 1023
```

- Nextflow  version 20.10.0
- nf-core/atacseq v1.2.1

**Comment by drpatelh** [comment]
Hi @chbk! Can you try and re-run the pipeline by adding `-resume` to the command? I have seen this error before but it seems to sort itself out for some reason if you resume with the same command.

**Comment by chbk** [comment]
Yeah I tried that and still got the same error. I ended up editing `main.nf` and renaming the duplicate channel to `ch_gene_bed_2` as a quick fix.

**Comment by drpatelh** [comment]
Sorry, this may actually be a bug. I was getting my wires crossed with another error. Would you mind sending my the full command and any custom configuration you used please?

**Comment by chbk** [comment]
Sure thing!

command:
```
nextflow run nf-core/atacseq \
  -c nextflow.config \
  --input samplesheet.csv \
  --outdir directory \
  --fasta 11.1.101.fa \
  --gtf 11.1.101.gtf \
  --macs_gsize 1576527533 \
  --mito_name MT \
  --save_reference \
  -resume
```

nextflow.config:
```
singularity {
  enabled = true
  runOptions = '-B /bank -B /work2 -B /work -B /save -B /home'
}

process {
  executor = 'slurm'
}
```

samplesheet.csv:
```
group,replicate,fastq_1,fastq_2
cd4,1,ATAC54_R1.fastq.gz,ATAC54_R2.fastq.gz
cd4,2,ATAC55_R1.fastq.gz,ATAC55_R2.fastq.gz
cd4,3,ATAC56_R1.fastq.gz,ATAC56_R2.fastq.gz
cd4,4,ATAC57_R1.fastq.gz,ATAC57_R2.fastq.gz
cd8,1,ATAC58_R1.fastq.gz,ATAC58_R2.fastq.gz
cd8,2,ATAC59_R1.fastq.gz,ATAC59_R2.fastq.gz
cd8,3,ATAC60_R1.fastq.gz,ATAC60_R2.fastq.gz
cd8,4,ATAC61_R1.fastq.gz,ATAC61_R2.fastq.gz
liver,1,ATAC62_R1.fastq.gz,ATAC62_R2.fastq.gz
liver,2,ATAC63_R1.fastq.gz,ATAC63_R2.fastq.gz
liver,3,ATAC64_R1.fastq.gz,ATAC64_R2.fastq.gz
```

**Comment by drpatelh** [comment]
Hi @chbk  ! Thanks for reporting and apologies for the delay in responding! We are about to release a much updated version of the pipeline that has been completely refactored to be written in Nextflow DSL2. When this is released, it would be great if you can let us know if the problem still persists. I will close this issue for now.
