### ISSUE TITLE
deepTools plotProfile plots a black graph

### ISSUE THREAD

**Issue by Akazhiel** [nf-core/atacseq#139]
The heatmaps produced by `deepTools` in the `mergedLibrary` step is fully black. Similar issue was opened and resolved here  https://github.com/deeptools/deepTools/issues/793.

What seems to cause this is sparsity in the data causing at the same time the matrixes generated by `deepTools` `computeMatrix` function to be filled with NaNs.

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/atacseq/issues/139. Thanks @Akazhiel !
