### ISSUE TITLE
Continue running pipeline at where it stopped last time

### ISSUE THREAD

**Issue by mavershang** [nf-core/atacseq#143]
Hi there. I am new to this atacseq pipeline.  If the first run failed at some stage, and I manually stepped in to fix that issue. Is there anyway I can resume the pipeline at the break point instead of running it again start from the beginning?

Thanks

**Comment by drpatelh** [comment]
Hi @mavershang ! Unfortunately not. This is more a Nextflow feature than the pipeline itself. See [here](https://www.nextflow.io/blog/2019/demystifying-nextflow-resume.html). If you have any specific issues come and find us on thenf-core Slack workspace via the links on the homepage 🙂
