### ISSUE TITLE
macs2 callpeak always writes to /tmp

### ISSUE THREAD

**Issue by medmaca** [nf-core/atacseq#144]
Currently no matter what you set $TMPDIR to the macs2 callpeak commands (MERGED_LIB_MACS2, MERGED_REP_MACS2) ignore this and write temporary files to /tmp.  On some HPC this causes issues.

The modification of the two callpeak commands to include **--tempdir** allows the user to modify the temp directory, e.g.:
```
    macs2 callpeak \\
        -t ${bam[0]} \\
        $broad \\
        -f $format \\
        -g $params.macs_gsize \\
        -n $prefix \\
        $pileup \\
        --keep-dup all \\
        --tempdir $TMPDIR \\
        --nomodel
```

It would be good to allow users to pass such a path to the callpeak commands.

**Comment by JoseEspinosa** [comment]
This will be possible to configure in the new DSL2 version of the pipeline that is planned to be released before the end of this month. You can see an example of how to pass additional parameters to process on [this](https://nfcore.slack.com/archives/CE8SSJV3N/p1666968742980909) slack message. Let us know if you need any further help 😄

**Comment by drpatelh** [comment]
@JoseEspinosa maybe we add a line to both MACS2 callpeak commands that does this by default and write to the work directory for the process?

Something like: `--tempdir ./tmp`. This has been set in a similar way for other tools that have shown similar issues.

https://github.com/nf-core/atacseq/blob/8431f9d9e3619739101569aade33bb53b2cc8c9d/conf/modules.config#L541-L549

https://github.com/nf-core/atacseq/blob/8431f9d9e3619739101569aade33bb53b2cc8c9d/conf/modules.config#L815-L822

**Comment by drpatelh** [comment]
Should be fixed in https://github.com/nf-core/atacseq/pull/246/commits/03adcea9782ee58b2e6fca40077a05b06b1efde9

Be great if you can test it out after the 2.0 release and let us know if it is fixed!

**Comment by drpatelh** [comment]
Ok. This isn't actually fixed. After I introduced it above for some reason the downstream processes aren't run:

```
[e7/024fe6] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_BIGWIG_PLOT_DEEPTOOLS:DEEPTOOLS_PLOTHEATMAP (OSMOTIC_STRESS_T0_PE_REP1)                        [100%] 6 of 6, cached: 6 ✔
[27/d1e90a] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_DEEPTOOLS_PLOTFINGERPRINT (OSMOTIC_STRESS_T0_PE_REP2)                                          [100%] 6 of 6, cached: 6 ✔
[3c/be91bb] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_CALL_ANNOTATE_PEAKS:MACS2_CALLPEAK (OSMOTIC_STRESS_T0_PE_REP2)                                 [100%] 6 of 6, cached: 6 ✔
[-        ] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_CALL_ANNOTATE_PEAKS:FRIP_SCORE                                                                 -
[-        ] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_CALL_ANNOTATE_PEAKS:MULTIQC_CUSTOM_PEAKS                                                       -
[-        ] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_CALL_ANNOTATE_PEAKS:HOMER_ANNOTATEPEAKS                                                        -
[-        ] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_CALL_ANNOTATE_PEAKS:PLOT_MACS2_QC                                                              -
[-        ] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_CALL_ANNOTATE_PEAKS:PLOT_HOMER_ANNOTATEPEAKS                                                   -
[-        ] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_CONSENSUS_PEAKS:MACS2_CONSENSUS                                                                -
[-        ] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_CONSENSUS_PEAKS:HOMER_ANNOTATEPEAKS                                                            -
[-        ] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_CONSENSUS_PEAKS:SUBREAD_FEATURECOUNTS                                                          -
[-        ] process > NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_CONSENSUS_PEAKS:DESEQ2_QC                                                                      -
```

Will remove again to get the release out and not to break things that have been working for a while already. But it should now be possible to provide this option via a custom config with the DSL2 implementation anyway.
