### ISSUE TITLE
Question on reducing size of Docker image

### ISSUE THREAD

**Issue by tamuanand** [nf-core/atacseq#153]
Hi @drpatelh @maxulysse 

I have a question: If one uses the [Dockerfile](https://github.com/nf-core/atacseq/blob/master/Dockerfile) along with the associated ```environment.yml``` files, the resultant image sizes are huge (at the least 2-3 GB). This would  be same with pretty much any nf-core project

Is there a way to reduce the size of the image?

I tried some of these techniques too but it did not help:
- https://uwekorn.com/2021/03/03/deploying-conda-environments-in-docker-cheatsheet.html
- https://jcristharif.com/conda-docker-tips.html

I also tried with Micromamba, the size still of the final Docker image is pretty huge
- https://github.com/mamba-org/micromamba-docker

Have any of you tried Mamba/Micromamba? I would be curious to know your findings

Thanks in advance

**Comment by JoseEspinosa** [comment]
I see that this question has been replied in nf-core/mag, will close it then.
