### ISSUE TITLE
Mini-issues in the reporting

### ISSUE THREAD

**Issue by ktrns** [nf-core/atacseq#157]
Hello there,

As usual, I am so glad I can run your pipeline for our clients! :-)

This time around, I found some irregularities in the MultiQC report, and just wanted to list them here for you: 
- "MACS2 peak FRiP score": Percentages are always at 100%, so the plot is not very meaningful if you have just 1 number
- "MERGED REP: featureCounts", "MERGED REP: DESeq2 PCA plot", "MERGED REP: DESeq2 sample similarity" are listing results for all samples, not merged replicates

And a mini-typo here: https://github.com/nf-core/atacseq/blob/master/docs/output.md
You are missing the "deseq2" in the path: 
- bwa/mergedLibrary/macs/<PEAK_TYPE>/consensus/<COMPARISON>/
- bwa/mergedLibrary/macs/<PEAK_TYPE>/consensus/sizeFactors/

Again @drpatelh - the pipelines are really useful, so thanks for your work. 
Best wishes
Katrin

**Comment by ktrns** [comment]
Hi there, 

Another one I just noticed: The sample colours in the "FRiP score" plots are flipped, compared to the other plots. 

Best wishes and thanks a lot,
Katrin

**Comment by JoseEspinosa** [comment]
Available in v2.1.0
