### ISSUE TITLE
Uneven number of control vs treatment samples in design

### ISSUE THREAD

**Issue by bounlu** [nf-core/atacseq#162]
Hi,

I am wondering if it's possible to run uneven number of samples for controls and treatments? such as 2 controls vs 4 treatments like:

```
group,replicate,fastq_1,fastq_2
control,1,/path/to/fastq/files/AEG588A1_S1_L002_R1_001.fastq.gz,/path/to/fastq/files/AEG588A1_S1_L002_R2_001.fastq.gz
control,2,/path/to/fastq/files/AEG588A2_S2_L002_R1_001.fastq.gz,/path/to/fastq/files/AEG588A2_S2_L002_R2_001.fastq.gz
treatment,1,/path/to/fastq/files/AEG588A4_S4_L003_R1_001.fastq.gz,/path/to/fastq/files/AEG588A4_S4_L003_R2_001.fastq.gz
treatment,2,/path/to/fastq/files/AEG588A5_S5_L003_R1_001.fastq.gz,/path/to/fastq/files/AEG588A5_S5_L003_R2_001.fastq.gz
treatment,3,/path/to/fastq/files/AEG588A6_S6_L003_R1_001.fastq.gz,/path/to/fastq/files/AEG588A6_S6_L003_R2_001.fastq.gz
treatment,4,/path/to/fastq/files/AEG588A7_S7_L003_R1_001.fastq.gz,/path/to/fastq/files/AEG588A7_S7_L003_R2_001.fastq.gz
```

**Comment by drpatelh** [comment]
Hi @bounlu ! Yep, that is absolutely fine. The pipeline will work with the replicates you provide as input even if they are unbalanced. Problems tend to generally arise when you have a single replicate in one group and multiple in others.

PS: Be awesome if you are able to [join the nf-core Slack](https://nf-co.re/join) workspace and find us on the #atacseq channel. You will be able to get help in real time from more people there for these sorts of questions. I tend to miss these issues at times.
