### ISSUE TITLE
MAKE_GENE_BED making 0kb .bed files

### ISSUE THREAD

**Issue by hcliedtke** [nf-core/atacseq#170]
Hi, I am using this really nice pipeline on my dataset. I am using an in-house reference genome and currently with the conda profile (I know that singularity or docker would be better, but for the time being this is the only option I have).

The pipeline fails at MERGED_LIB_PLOTPROFILE and I think I have traced it back to the fact that the .bed file supplied to the computeMatrix function is empty (0 kb).

I have looked at the report and execution report and I believe the problem is with MAKE_GENE_BED, which executes the script `gtf2bed foo.gtf > foo.bed`. It seems to be that this should be `gtf2bed < foo.gtf > foo.bed`. Could this be?

Thanks for your help. I am relatively new to nextflow pipelines, so apologies if I am not expressing my issue in the best way.

**Comment by drpatelh** [comment]
Hi @hcliedtke ! Thanks for reporting and apologies for the delay in responding! We are about to release a much updated version of the pipeline that has been completely refactored to be written in Nextflow DSL2. When this is released, it would be great if you can let us know if the problem still persists. I will close this issue for now.

For faster, real-time help for these sorts of things please join the #atacseq channel on the nf-core Slack workspace. You can join via the link below:
https://nf-co.re/join

**Comment by hcliedtke** [comment]
Fantastic. I will try the new pipeline as soon as it's out!

**Comment by hcliedtke** [comment]
Hi @drpatelh, I believe this is still and issue with the latest DSL2 release.
