### ISSUE TITLE
Bug with design matrix: No such variable: ch_design_reads_csv

### ISSUE THREAD

**Issue by dekan-alexander** [nf-core/atacseq#176]
Hello! I am trying to run tests for nextflow atac seq, but they fail:

`nextflow run nf-core/atacseq -profile test,docker`

Output:
N E X T F L O W  ~  version 22.04.0
Launching `https://github.com/nf-core/atacseq` [elegant_fermi] DSL2 - revision: 1b3a832db5 [master]
Run Name             : elegant_fermi
Data Type            : Paired-End
Design File          : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/design.csv
Genome               : Not supplied
Fasta File           : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genome.fa
GTF File             : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genes.gtf
Mitochondrial Contig : MT
MACS2 Genome Size    : 1.2E+7
Min Consensus Reps   : 1
MACS2 Narrow Peaks   : No
MACS2 Broad Cutoff   : 0.1
Trim R1              : 0 bp
Trim R2              : 0 bp
Trim 3' R1           : 0 bp
Trim 3' R2           : 0 bp
NextSeq Trim         : 0 bp
Fingerprint Bins     : 100
Save Genome Index    : No
Max Resources        : 6 GB memory, 2 cpus, 12h time per job
Container            : docker - nfcore/atacseq:1.2.1
Output Dir           : ./results
Launch Dir           : /home/dekan
Working Dir          : /home/dekan/work
Script Dir           : /home/dekan/.nextflow/assets/nf-core/atacseq
User                 : dekan
Config Profile       : test,docker
Config Description   : Minimal test dataset to check pipeline function

No such variable: ch_design_reads_csv

 Check script '.nextflow/assets/nf-core/atacseq/main.nf' at line: 360 or see '.nextflow.log' file for more details

**Comment by i-pletenev** [comment]
Hi, I'm having the same issue. Downgrading to older nextflow version helps: `conda install -c bioconda nextflow=21.10.6`.

**Comment by JoseEspinosa** [comment]
The problem is that nextflow has enabled DSL2 as default on version `22.04.0`and the current atacseq version is still a DSL1 pipeline (see [this](https://www.nextflow.io/blog/2022/evolution-of-nextflow-runtime.html) post).
The easiest fix is to add the `-dsl1`  flag at the end of your command, e.g.: `NXF_VER=22.04.0 nextflow run nf-core/atacseq -profile test,docker -dsl1`

**Comment by dekan-alexander** [comment]
> The problem is that nextflow has enabled DSL2 as default from version `22.04.0`and the current atacseq version is still a DSL1 pipeline (see [this](https://www.nextflow.io/blog/2022/evolution-of-nextflow-runtime.html) post). The easiest fix is to add the `-dsl1` flag at the end of your command when using new nextflow versions, e.g.: `NXF_VER=22.04.0 nextflow run nf-core/atacseq -profile test,docker -dsl1`

Thank you! This one works!

**Comment by JoseEspinosa** [comment]
Are you sure? This is a Nextflow option and from Nextflow docs:
*"Nextflow options use a single dash prefix, e.g. -foo. Do not confuse with double dash notation, e.g. --foo, which is instead used for [Pipeline parameters](https://www.nextflow.io/docs/latest/cli.html?highlight=cli#cli-params)."*
I just tried myself and I can make it work with two dashes :thinking:
