### ISSUE TITLE
--macs_gsize option 

### ISSUE THREAD

**Issue by StevenWingett** [nf-core/atacseq#182]
I recently opened a GitHub issue for the nf-core chipseq pipeline.  This potential problem applies to atacseq pipeline as well.

The issue regards the choice of genome size specified with the --macs_gsize option.  Following the advice of Harshil Patel, I am opening another issue here in addition to that posted on the chipseq GitHub page.

For further details on the issue, please see:
https://github.com/nf-core/chipseq/issues/280

Many thanks,

Steven

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/atacseq/pull/203
