### ISSUE TITLE
Update test-datasets

### ISSUE THREAD

**Issue by JoseEspinosa** [nf-core/atacseq#189]
The input file [here](https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/design.csv) is deprecated update to something similar to [this](https://github.com/nf-core/atacseq/blob/dev/assets/test.csv).

**Comment by drpatelh** [comment]
Done in https://github.com/nf-core/test-datasets/commit/6f22036db55cd0e99893953591d4955274a5215c https://github.com/nf-core/test-datasets/commit/e0a715dc5d90c560c1da06ae01be9dd38f96fd7d
