### ISSUE TITLE
BWA index error

### ISSUE THREAD

**Issue by cindyli9888** [nf-core/atacseq#194]
Hi,

I was able to run the test file successfully. However, when I tried with my own data, this error occurred:

```
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.
```

The full error message was:

```
Error executing process > 'BWA_MEM (0h_R1_T1)'

Caused by:
  Process `BWA_MEM (0h_R1_T1)` terminated with an error exit status (1)

Command executed:

  bwa mem \
      -t 1 \
      -M \
      -R '@RG\tID:0h_R1_T1\tSM:0h_R1\tPL:ILLUMINA\tLB:0h_R1_T1\tPU:1' \
       \
      BWAIndex/genome.fa \
      0h_R1_T1_1_val_1.fq.gz 0h_R1_T1_2_val_2.fq.gz \
      | samtools view -@ 1 -b -h -F 0x0100 -O BAM -o 0h_R1_T1.Lb.bam -

Command exit status:
  1

Command output:
  (empty)

Command error:
  [main_samview] fail to read the header from "-".
```

Is there anything I can do to fix this?
Thank you!

Cindy

**Comment by ewels** [comment]
Hmm, this is a bit of an obscure error. Are your FastQ files definitely as you expect? Not corrupted, with some reads and so on? It sounds to me like the alignment is failing at a guess, but there's not much to go on here.

**Comment by drpatelh** [comment]
Hi @ ! Thanks for reporting! We are about to release a much updated version of the pipeline that has been completely refactored to be written in Nextflow DSL2. When this is released, it would be great if you can let us know if the problem still persists. I will close this issue for now.

For faster, real-time help for these sorts of things please join the #atacseq channel on the nf-core Slack workspace. You can join via the link below:
https://nf-co.re/join
