### ISSUE TITLE
Repository may be corrupted

### ISSUE THREAD

**Issue by wbszhu** [nf-core/atacseq#196]
Hi,
when i run this pipeline, the error occured:
```
Can't find git repository config file -- Repository may be corrupted: /public/home/luzhang/.nextflow/assets/nf-core/atacseq
```
Can you give me some suggestions? thanks~

**Comment by wbszhu** [comment]
Hi,
I try to do like you. the other error occured:
https://github.com/nf-core/atacseq.git: cannot open git-upload-pack

**Comment by maxulysse** [comment]
what's your command line when running the pipeline?

**Comment by maxulysse** [comment]
can you try:
```
nextflow pull nf-core/atacseq -r 1.2.2
```

**Comment by wbszhu** [comment]
it is also report:
```
nextflow pull nf-core/atacseq -r 1.2.2
Checking nf-core/atacseq ...
https://github.com/nf-core/atacseq.git: cannot open git-upload-pack
```

**Comment by maxulysse** [comment]
can you try:
```
nextflow pull hello
```

**Comment by wbszhu** [comment]
report like it:
```
nextflow pull hello
Checking hello ...
https://github.com/nextflow-io/hello.git: cannot open git-upload-pack
```

**Comment by maxulysse** [comment]
Can you do:
```
ls -l  ~/.nextflow/assets/nextflow-io/hello
```
and if you have something:
```
cd  ~/.nextflow/assets/nextflow-io/hello
git status
```
and copy paste the results

**Comment by wbszhu** [comment]
Cause the command "next flow, pull hello" was not succeed.

ls -l  ~/.nextflow/assets/nextflow-io/hello
```
ls: cannot access '/public/home/luzhang/.nextflow/assets/nextflow-io/hello': No such file or directory
```

cd  ~/.nextflow/assets/nextflow-io/hello
```
-bash: cd: /public/home/luzhang/.nextflow/assets/nextflow-io/hello: No such file or directory
```

git status
```
fatal: Not a git repository (or any parent up to mount point /public)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by ewels** [comment]
It sounds like there's something fishy going on with your Nextflow installation. I don't think it's related to this pipeline specifically.

I would try removing your whole Nextflow home directory (`NXF_HOME` env var if set, default `~/.nextflow`) and trying again with the `hello` pipeline which is as simple as they come. If you're still having trouble, please ask for help on Slack.

Closing this issue as it's not a problem with this pipeline.
