### ISSUE TITLE
bwa: command not found

### ISSUE THREAD

**Issue by xnr13** [nf-core/atacseq#204]
```
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'BWA_INDEX (genome.fasta)'

Caused by:
  Process `BWA_INDEX (genome.fasta)` terminated with an error exit status (127)

Command executed:

  bwa index -a bwtsw genome.fasta
  mkdir BWAIndex && mv genome.fasta* BWAIndex

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: bwa: command not found

Work dir:
  /media/ATACseq_nf-core_atacseq/work/61/60251f1c01ef5bdc9f5c81c5cdcc95

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

**Comment by ewels** [comment]
Please post the full Nextflow log, not just the error message. It sounds like something isn't working with the singularity setup for you.

**Comment by drpatelh** [comment]
Hi @jianxinwang ! Thanks for reporting! We are about to release a much updated version of the pipeline that has been completely refactored to be written in Nextflow DSL2. When this is released, it would be great if you can let us know if the problem still persists and attach the requested files. I will close this issue for now.

This doesn't sound like a pipeline issue so it may be better to get faster, real-time help for these sorts of things in the #atacseq channel on the nf-core Slack workspace. You can join via the link below:
https://nf-co.re/join
