### ISSUE TITLE
Can you run pipeline with different genomes at once?

### ISSUE THREAD

**Issue by tzvi909** [nf-core/atacseq#231]
Hi,

I was wondering can you run the pipeline from trimmed FQs and specify that you want different FastQs to align to different genomes in the design csv? -i.e. x samples align with GRCh38 + a viral one, y samples align with GRCh38 + a different viral strain and z samples align with GRCh38 only?

Many Thanks,

Joshua

**Comment by JoseEspinosa** [comment]
Hi @tzvi909, 
First sorry for the late reply. I am afraid this is not possible with the current implementation of the pipeline.

**Comment by ktrns** [comment]
HI @JoseEspinosa - May I close the issue?

**Comment by JoseEspinosa** [comment]
Yes, left it open in case @tzvi909 had any further questions. Will close it now.
