### ISSUE TITLE
Robustness: modules/nf-core/bwa/mem/main.nf

### ISSUE THREAD

**Issue by hukai916** [nf-core/atacseq#256]
### Description of the bug

The following line 
https://github.com/nf-core/atacseq/blob/0add18866a5f095e93b8ec345a12b76d675f4af9/modules/nf-core/bwa/mem/main.nf#L28

should be updated to reflect that of:

https://github.com/nf-core/modules/blob/f4bbd81636426c4060ce7ff421f4500c5a831e29/modules/nf-core/bwa/mem/main.nf#L28

**Comment by maxulysse** [comment]
It's in `dev` already, will be there in the coming release

**Comment by maxulysse** [comment]
cf: https://github.com/nf-core/atacseq/blob/f8af6733468ed9d74326d293ad8754552e0c131b/modules/nf-core/bwa/mem/main.nf#L28
