### ISSUE TITLE
General statistics table in MultiQC report

### ISSUE THREAD

**Issue by berguner** [nf-core/atacseq#269]
### Description of feature

Hi,
I realised that the `atacseq` pipeline doesn't generate a `General Statistics` table in the MultiQC report. Many other `nf-core` pipelines have such a table and it would be nice to have it also for the `atacseq` pipeline. Below metrics would be of particular interest:
- Raw read count
- Aligned read count/rate
- Duplication rate
- Trimmed read count/rate
- Peak count
- FRiP score

**Comment by JoseEspinosa** [comment]
Hi @berguner, I am not sure to understand, in the [current](https://nf-co.re/atacseq/results#atacseq/results-1b3a832db5a53c92c2c89a4d6d79455e860461ad/multiqc/broadPeak/multiqc_report.html) multiqc report I'd say all the metrics above are reported, aren't they?

**Comment by JoseEspinosa** [comment]
Sorry, after a second read I understood what you mean. To make render the general statistics information in the multiqc report, you can provide a custom multiqc config as the one below (saved say as `custom_multiqc.config`)
```
run_modules:
  - custom_content
  - fastqc
  - cutadapt
  - samtools
  - picard
  - preseq
  - featureCounts
  - deeptools
  - general_stats
```
And then adding to the your nextflow command the `----multiqc_config` option e.g. `nextflow run ... --multiqc_config custom_multiqc.config`.
I will close this issue now but let us know if you need any further information.
