### ISSUE TITLE
zipped fasta file doesn't work

### ISSUE THREAD

**Issue by rodriguesk** [nf-core/atacseq#277]
### Description of the bug

I’m getting this error and I’m wondering how to solve it. I’m using the genome mm39 (which is new and not in igenome) so I’m trying to provide custom genome to the pipeline, I’m getting the following error and I noticed that it is fixed when I unzip the fasta file.

### Command used and terminal output

```console
Error executing process > 'NFCORE_ATACSEQ:ATACSEQ:PREPARE_GENOME:CUSTOM_GETCHROMSIZES (null)'

Caused by:
  Not a valid path value type: groovyx.gpars.dataflow.DataflowVariable (DataflowVariable(value=null))
```

### Relevant files

In the config file I’m using these in the params section:
fasta     = '/oak/stanford/groups/smontgom/kameronr/methylseq/JG97/genomes/GRCm39_fasta/GRCm39.genome.fa.gz'
bwa_index = '/oak/stanford/groups/smontgom/kameronr/methylseq/JG97/genomes/GRCm39_fasta/'                                                                                                                                                         
gtf       = '/oak/stanford/groups/smontgom/kameronr/methylseq/JG97/genomes/GRCm39_gtf/Mus_musculus.GRCm39.106.gtf'
macs_gsize = 2728222451

**Comment by sergpolly** [comment]
exact same here.
crashes with the error message above when fasta is compressed, proceeds beautifully when fasta is a text file ...
Have to admit it wasn't easy to debug - as all of the work folders are empty and .nextflow.log isn't very informative in this case

**Comment by JoseEspinosa** [comment]
Should be fixed now in `dev` in case you want to give it a try.

**Comment by JoseEspinosa** [comment]
Will close this issue now, feel free to reopen it if you find any further issue.
