### ISSUE TITLE
Terminated by the external system

### ISSUE THREAD

**Issue by CLAIRE-cuhk** [nf-core/atacseq#281]
### Description of the bug

Hi developer,

We were trying to run nfcore-atacseq pipeline in a cluster with the script and design table attached. 
[nfcore.txt](https://github.com/nf-core/atacseq/files/11576896/nfcore.txt)
[design.txt](https://github.com/nf-core/atacseq/files/11576878/design.txt)

We encounter the following issue after it runs for a few hours:

Error executing process > 'MERGED_LIB_BAM_FILTER (4_R1)'
Caused by:
  Process `MERGED_LIB_BAM_FILTER (4_R1)` terminated for an unknown reason -- Likely it has been terminated by the external system

Could you please help with this issue?
Would the nfcore atac-seq pipeline allow us to put more than two experimental groups in one design table? We are using a testing sample set with 6 groups and each with only one replicate. 
Thank you in advance.

**Comment by JoseEspinosa** [comment]
The error message you are reporting suggests that your cluster killed the process for some reason typically because the default resources like time, memory and cpus set in the pipeline aren't enough for that process to finish.
