### ISSUE TITLE
Errors in MERGED_LIBRARY_BAM_TO_BIGWIG:UCSC_BEDGRAPHTOBIGWIG

### ISSUE THREAD

**Issue by AAAAAbetter** [nf-core/atacseq#290]
### Description of the bug

When I run to this step of BAM_TO_BIGWIG, it says the following error, how can I solve this?

### Command used and terminal output

```console
Error executing process > 'NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_BAM_TO_BIGWIG:UCSC_BEDGRAPHTOBIGWIG (control_REP1)'

Caused by:
  Process `NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_BAM_TO_BIGWIG:UCSC_BEDGRAPHTOBIGWIG (control_REP1)` terminated with an error exit status (255)

Command executed:

  bedGraphToBigWig \
      control_REP1.mLb.clN.bedGraph \
      GRCh38.primary_assembly.genome.fa.sizes \
      control_REP1.mLb.clN.bigWig
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_BAM_TO_BIGWIG:UCSC_BEDGRAPHTOBIGWIG":
      ucsc: 377
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  control_REP1.mLb.clN.bedGraph is not case-sensitive sorted at line 12791860.  Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.

Work dir:
  /home/data/yaoyanxin/ABC_model_20230608/nf-ATAC/work/d3/28b5fcda3e5ae068adeba1c121dcb1

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Relevant files

[.nextflow.log](https://github.com/nf-core/atacseq/files/11704026/default.nextflow.log)

### System information

nf-core/atac-seq 2.0

**Comment by JoseEspinosa** [comment]
This seems to be an error related to your environment variables settings. See [here](https://groups.google.com/a/soe.ucsc.edu/g/genome/c/utzMtbvIBVQ?pli=1). Also, we had a similar issue on the rnaseq pipeline some time ago, fixed on [this](https://github.com/nf-core/rnaseq/pull/480) PR. You could try to set `LANG=C` or `LC_COLLATE=C` and see whether it works.

**Comment by JoseEspinosa** [comment]
This should be fixed now in `dev`, in case you want to give it a try

**Comment by AAAAAbetter** [comment]
> This should be fixed now in `dev`, in case you want to give it a try

Yes! Thanks for your help, I have successfully run this pipline!

**Comment by JoseEspinosa** [comment]
OK, thanks for reporting back, then I will close the issue now, let us know if you have any further question.
