### ISSUE TITLE
ERROR ~ Cannot find latest version of nf-validation plugin

### ISSUE THREAD

**Issue by JiahuaQu** [nf-core/atacseq#305]
### Description of the bug

I ran the atacseq-dev pipeline in our institute's HPC but had the error:
ERROR ~ Cannot find latest version of nf-validation plugin.

Then I went to the plugin folder to install plugin manually:
nextflow plugin install nf-validation

But the same error came again.

When I downloaded the pipeline, only the first option, dev version, could be downloaded completely whereas other versions always had errors and their downloadings were interrupted incompletely.

Can you help with this error? Thank you very much.

[my.log](https://github.com/nf-core/atacseq/files/12040636/my.log)

### System information

nextflow   # version: 22.10.6
HPC
SGE
Singularity
CentOS
version: dev  nf-core-atacseq-dev

**Comment by JoseEspinosa** [comment]
Hi, I asked the nf-validation team (see thread in the nf-core slack [here](https://nfcore.slack.com/archives/C056RQB10LU/p1689267937384229)) and it seems to be an error fetching from github so maybe you had a problem with the internet connection. Maybe worth trying again and if the problem persists please let us know.

**Comment by JoseEspinosa** [comment]
I will close this issue seems most likely is not a problem of the pipeline

**Comment by AAAAAbetter** [comment]
Hello, I have the same problem loading version 2.1.2 atacseq pipline,
And I get the same error 'Cannot find latest version of nf-validation plugin' while downloading, is there any way to configure the plugin locally


> Hi, I asked the nf-validation team (see thread in the nf-core slack [here](https://nfcore.slack.com/archives/C056RQB10LU/p1689267937384229)) and it seems to be an error fetching from github so maybe you had a problem with the internet connection. Maybe worth trying again and if the problem persists please let us know.

**Comment by JoseEspinosa** [comment]
Hi @AAAAAbetter, you can try to download it using the command line see [here](https://www.nextflow.io/docs/latest/plugins.html#configuration)
