### ISSUE TITLE
ERROR ~ A process input channel evaluates to null -- Invalid declaration ` val mito_name`

### ISSUE THREAD

**Issue by JiahuaQu** [nf-core/atacseq#306]
### Description of the bug

Hi, I had problems in downloading the complete and correct pipelines. I tried many versions but always failed with the similar errors: 
ERROR    Cannot parse container string in                                 
         'nf-core-atacseq-2.0/workflow/modules/nf-core/bowtie2/align/main.
         nf':                                                             
                                                                          
             ${ workflow.containerEngine ==                               
                                                                          
         ⚠ Skipping this singularity image.. 

[downloading with singularity images.txt](https://github.com/nf-core/atacseq/files/12044857/downloading.with.singularity.images.txt)

Then I determied to download without singularity images.
However, when running the program in my institute's HPC, the same error always showed:
ERROR ~ A process input channel evaluates to null -- Invalid declaration `
val mito_name`
[my.log](https://github.com/nf-core/atacseq/files/12044871/my.log)
[test.sh.o9702320.txt](https://github.com/nf-core/atacseq/files/12044872/test.sh.o9702320.txt)

Hope get your help. Thank you.

### System information

nextflow   # version: 22.10.6

HPC
GSE
With or without singularity
CentOS

I tried various versions:
# nf-core-atacseq-dev
# nf-core-atacseq-2.0
# nf-core-atacseq-master
# nf-core-atacseq-1.2.2
# nf-core-atacseq-modules-update

**Comment by JoseEspinosa** [comment]
Yes, these are two known bugs of the current released version that are fixed in the `dev` version of the pipeline see #270 and #286. Anyway, if you want to use the release version you can:
1- Just can use the nf-core download and do not care about the error. The reason is that the the bwa image will be downloaded anyways since bwa/mem uses the same image and there it is correctly tagged. More info about the `download` command [here](https://nf-co.re/tools#downloading-pipelines-for-offline-use).
2- Just provide an empty or a fake `mito_name` adding this to your command `--mito_name ''` or `--mito_name dummy`

**Comment by JiahuaQu** [comment]
> Yes, these are two known bugs of the current released version that are fixed in the `dev` version of the pipeline see #270 and #286. Anyway, if you want to use the release version you can: 1- Just can use the nf-core download and do not care about the error. The reason is that the the bwa image will be downloaded anyways since bwa/mem uses the same image and there it is correctly tagged. More info about the `download` command [here](https://nf-co.re/tools#downloading-pipelines-for-offline-use). 2- Just provide an empty or a fake `mito_name` adding this to your command `--mito_name ''` or `--mito_name dummy`

Thank you for your answer.
Now I used the version 2.0 and added the command `--mito_name ''`.
Although the program could be ran further than before, there was a new error with the BWA-MEM. Details in the attachment.
Hope get further help. Thank you again.
[new_error.txt](https://github.com/nf-core/atacseq/files/12051762/new_error.txt)

**Comment by JoseEspinosa** [comment]
Since this is being discussed already in https://github.com/nf-core/chipseq/issues/356. I close this issue now in favour of the former.
