### ISSUE TITLE
[Question]: macs2 callpeak outputs - narrowPeak vs broadPeak

### ISSUE THREAD

**Issue by tamuanand** [nf-core/atacseq#318]
Hi,

I have a question on this line of code here

https://github.com/nf-core/atacseq/blob/415795d3c14fb296c6418b427279ca34ab976844/modules/nf-core/macs2/callpeak/main.nf#L15

```
output:
tuple val(meta), path("*.{narrowPeak,broadPeak}"), emit: peak
```

If I am correct, this means that both `*.narrowPeak and *.broadPeak` are mandatory outputs expected by the process.

As far as I know, `macs2 callpeak` will only generate one or the other 
- with `--broad` it will generate `*_peaks.broadPeak` file
- if you do not specify `--broad`, then it will generate `*_peaks.narrowPeak`

Am I missing anything?

**Comment by chlazaris** [comment]
@tamuanand It generates either, not both

**Comment by tamuanand** [comment]
Thanks @chlazaris
