### ISSUE TITLE
Fix double slash in directory urls

### ISSUE THREAD

**Issue by jhanifen** [nf-core/atacseq#332]
### Description of the bug

When using newer versions of Nextflow, the follow error may occur when moving files. 

java.lang.IllegalArgumentException: I/O not allowed on dot-dirs or extra slashes when !permitEmptyPathComponents:

This is due to the path to the files having a double slash // 

Example:
macs2//narrow

### Relevant files

conf/modules.config

**Comment by jhanifen** [comment]
[0001-fix-double-slash-logic.patch](https://github.com/nf-core/atacseq/files/12434002/0001-fix-double-slash-logic.patch)

patch for a fix

**Comment by bjlang** [comment]
#355 implements your patch. Thank you for that.
