### ISSUE TITLE
URGENT: pin nf-validation version

### ISSUE THREAD

**Issue by nvnieuwk** [nf-core/atacseq#351]
### Description of the bug

To prevent breaking this pipeline in the near future, the nf-validation version should be pinned to version 1.1.3 like:

```
plugins {
    id 'nf-validation@1.1.3'
}
```

**Comment by JoseEspinosa** [comment]
Already in dev, see [here](https://github.com/nf-core/atacseq/blob/a4b97cbeb80ac3db20aa53f2ade1eab3261487cd/nextflow.config#L242-L244)

**Comment by nvnieuwk** [comment]
Awesome, thank you! When will this be released?
