### ISSUE TITLE
Improve website on parameters section Alignment Options for argument --save_unaligned

### ISSUE THREAD

**Issue by aghr** [nf-core/atacseq#359]
### Description of feature

The description of parameter --save_unaligned reads: "Where possible, save unaligned reads from either STAR, HISAT2 or Salmon to the results directory." but if I got it right then does the pipeline offer mappers BWA, Bowtie2, and STAR, but not HISAT2 nor Salmon.

**Comment by JoseEspinosa** [comment]
Thanks for reporting @aghr, this is now fixed on the `dev` branch.
Done in #368
