### ISSUE TITLE
Unable to join Slack channel

### ISSUE THREAD

**Issue by JessicaHacheney** [nf-core/atacseq#364]
### Description of the bug

I would love to join your Slack channel, but I am unable to request an invite.
The link goes to this page:  https://nfcore.slack.com/signup#/domain-signup
It always asks for an @qbic.uni-tuebingen.de or @seqera.io address.

There is also this page:
https://nfcore.slack.com/?redir=%2Farchives%2Fgithub-invitations%3Fname%3Dgithub-invitations
But when I enter my email address there and then enter the code, it just tells me I don't have an account in the workspace.

Would be great if you could help.

**Comment by JoseEspinosa** [comment]
Sorry for the late response. Using [this](https://nf-co.re/join/slack) link should allow you to join nf-core slack.

**Comment by adoig-umass** [comment]
Hi Jose,
perhaps these links become deactivated over time? I also am attempting to access the slack but am having the same challenges. Is there a fresh invite that could be provided?

**Comment by adoig-umass** [comment]
Issue must have been on my end, link provided by JoseEspinosa to JessicaHecheny now works for me also.

**Comment by JoseEspinosa** [comment]
@adoig-umass actually you are right, the link has to be reactivated from time to time.
Will close it now as it is fixed now
