### ISSUE TITLE
Docs: Add example plot images

### ISSUE THREAD

**Issue by ewels** [nf-core/atacseq#41]
The current atacseq output documentation is excellent, but a bit on the wordy side 😉 

The pipeline generates loads of lovely plots - both directly and from MultiQC. It would make the docs much easier to read (and more impressive!) if examples of these were included.

**Comment by drpatelh** [comment]
Thanks! But there's never too many words in documentation :scream: 

Yeah, the `atacseq` pipelines seems like ancient history with all the other stuff I've been working on. That, and a couple of other things have been on my TODO list to bring it in line with the `chipseq` pipeline....should have created an issue :+1:

**Comment by drpatelh** [comment]
Hows this @ewels ?
https://github.com/drpatelh/nf-core-atacseq/blob/master/docs/output.md

Pretty much the same as the `chipseq` docs now. Just have to re-generate a couple of images and finesse and then Ill create a PR.

**Comment by ewels** [comment]
Much better! 🤩

**Comment by drpatelh** [comment]
Will be fixed in https://github.com/nf-core/atacseq/pull/53
