### ISSUE TITLE
Remove not sorted bams after sorting 

### ISSUE THREAD

**Issue by xeccm** [nf-core/atacseq#42]
It would be nice if after sorting the .bam the unsorted ones were automatically deleted. This would save space.

**Comment by drpatelh** [comment]
Hi @xeccm ! The unsorted bam files will be generated and stored in the `work/` directory anyway, and it is encouraged to delete this directory when the pipeline finishes successfully to remove all of the intermediate files generated from the pipeline. By default, only the final filtered bam files are copied to the `results/` directory.

The intermediate bam files are only copied to the `results/` directory if you use the `--saveAlignedIntermediates` parameter.

Does that resolve this issue?

Are you having issues with storage when running the pipeline?

**Comment by drpatelh** [comment]
The auto-removal of intermediate files is more a core Nextflow issue:
https://github.com/nextflow-io/nextflow/issues/165

**Comment by drpatelh** [comment]
Assuming this is resolved now unless you have more to add @xeccm ? If so, feel free to reopen 👍
