### ISSUE TITLE
Images missing in Documentation/results_description.html

### ISSUE THREAD

**Issue by ktrns** [nf-core/atacseq#43]
Hi there, 

I was running your atacseq pipeline yesterday for the first time, and I am going through the results. 

When I look at results_description.html, I see links to plots, e.g. "MultiQC - Cutadapt trimmed sequence plot". These plots cannot be opened. Looking at the html itself, it should be: images/mqc_cutadapt_plot.png, but the folder isn't there. 

Are these plots example plots, as I find them in your GitHub atacseq/docs/images, that should have been copied? 

Looking forward to hearing from you, 
best wishes and thanks in advance
Katrin

**Comment by drpatelh** [comment]
Hi @ktrns ! Good spot! I have always worked off the docs on the GitHub page which is why I haven't spotted this before. They should be exactly the same:
https://github.com/nf-core/atacseq/blob/master/docs/output.md

This may be a bug related to https://github.com/nf-core/atacseq/issues/41 because the images aren't embedded directly in the markdown document. I'll have a proper look when I get into the office :+1:

**Comment by ktrns** [comment]
@drpatelh, Thanks again! 

Yes, they seem related. When I opened results_description.html for the first time, I was expecting the plots from *my* project. When I couldn't open the linked plots and looked this up in your script, I realised it would have been example plots only anyway. I am not sure if this will help or is misleading in the end. 

The way I understood #41 is that it would be nice to see the plots from *our* projects, but then again you included them in the MultiQC html. If I understand it correctly now, results_description.html is only a description of what results to expect and where to find them. The actual plots can be opened one by one in the respective folders, or by looking that the MultiQC report, correct?  

Best wishes and thanks in advance
Katrin

**Comment by drpatelh** [comment]
So it appears that this may be a bug in the pipeline template because the script that generates `results_description.html` doesnt copy across the images embedded in `output.md`.

**Comment by drpatelh** [comment]
https://github.com/nf-core/tools/issues/391

**Comment by ewels** [comment]
> If I understand it correctly now, results_description.html is only a description of what results to expect and where to find them. The actual plots can be opened one by one in the respective folders, or by looking that the MultiQC report, correct?

Correct - `results_description.html` is just a local copy of the bundled documentation (which is static).

**Comment by drpatelh** [comment]
Closing in favour of https://github.com/nf-core/tools/issues/391

@ktrns This will eventually be resolved in the template and subsequently propagated into the pipeline code via the automated syncing we have in place for pipelines 👍
