### ISSUE TITLE
Output directory missing: macs2/consensus/deseq2

### ISSUE THREAD

**Issue by ktrns** [nf-core/atacseq#44]
Hi again, 

I am going through Documentation/results_description.html to understand which output I have. I do not find bwa/mergedLibrary/macs2/consensus/deseq2. Instead, I find bwa/mergedLibrary/macs/consensus and qc, i.e. no macs2 and no further deseq2 subdirectories. Can you comment on that? Were you still running macs2, but no deseq2? 

Many thanks in advance! 
Katrin

**Comment by drpatelh** [comment]
Hi @ktrns ! You will only find the `deseq2` directory if you have replicate groups in your design file. Can you send me `design.csv` here please?

**Comment by ktrns** [comment]
Hi @drpatelh, Thanks for your quick reply! We only have one replicate per group, so that would explain it. But the folder is still called 'macs' rather than 'macs2', as it is mentioned in the results_description.html.

**Comment by drpatelh** [comment]
Yep. It should be `macs` and not `macs2` in the documentation :+1: 

This discrepancy also exists in the `nf-core/chipseq` documentation which will need to be corrected too.
https://github.com/nf-core/chipseq/blob/master/docs/output.md

**Comment by ktrns** [comment]
@drpatelh, great, thanks for letting me know. I will soon run the chipseq pipeline too, so good to know.

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/atacseq/pull/49
