### ISSUE TITLE
Wrong x-axis scale for the HOMER: Peak annotation Counts tab plot? 

### ISSUE THREAD

**Issue by ktrns** [nf-core/atacseq#45]
Hi there, 

One more issue: Looking at the MultiQC report, the HOMER: Peak annotation plot, Counts tab, the plot seems to be on the wrong x-axis scale. The scale seems to be that of the Percentages tab (0-100), is it? 

The reason why I think something might be wrong is that for the Percentages tab, we get peaks assigned to all genomic features; not for the Counts tab. 

Let me know what you think. 
Thank you in advance!
Best wishes
Katrin

**Comment by drpatelh** [comment]
This is great feedback! Again, you are absolutely right but Im not sure what the fix is at the moment. Will need to look into it further because I am passing these values as custom content to MultiQC and they are the actual counts per feature. In any case, these values should be apparent if you just hover over the percentages plot :+1: 

```
#id: 'mlib_peak_annotation'
#section_name: 'HOMER: Peak annotation (merged library)'
#description: "is generated by calculating the proportion of peaks assigned to genomic features by
#              <a href='http://homer.ucsd.edu/homer/ngs/annotation.html' target='_blank'>HOMER annotatePeaks.pl</a>."
#plot_type: 'bargraph'
#anchor: 'nfcore_atacseq-mlib_peak_annotation'
#pconfig:
#    title: 'Peak to feature %'
#    ylab: 'Feature %'
#    ymax: 100
#    ymin: 0
#    cpswitch_c_active: false
sample	exon	Intergenic	intron	promoter-TSS	TTS
SAMPLE1_R1	8786	51857	44201	9309	2135
SAMPLE2_R1	9212	46819	39317	9397	2015
SAMPLE3_R1	8876	50524	41849	9695	1871
```

**Comment by drpatelh** [comment]
Maybe because Im hard-coding `ymin` and `ymax` in the header of the custom config file :thinking:

**Comment by drpatelh** [comment]
@ktrns This will be fixed in https://github.com/nf-core/atacseq/pull/52

**Comment by drpatelh** [comment]
![mqc_mplplot_ucfibasymd-1](https://user-images.githubusercontent.com/23529759/66655103-6e540c80-ec33-11e9-86cb-462869bb21a8.png)

![mqc_mplplot_ucfibasymd-1 (1)](https://user-images.githubusercontent.com/23529759/66655120-73b15700-ec33-11e9-864d-b9c301bc3728.png)
