### ISSUE TITLE
Bug in MultiQC's picard-insert-size plot

### ISSUE THREAD

**Issue by jinmingda** [nf-core/atacseq#51]
The y value of the data points in MultiQC's Picard insert size plot is almost twice as those in the insert size plot generated by Picard (`bwa/mergedLibrary/picard_metrics/pdf/*_insert_size_histogram.pdf`). I think this is probably caused by binning in MultiQC's [linegraph function](https://github.com/ewels/MultiQC/blob/f275ec9209ea4dd32cd2f2e62becd327fa866c44/multiqc/plots/linegraph.py#L457). So I tried to increase the value of `smooth_points` in multiqc config from 1000 to 10000, but it doesn't seem to work.

![image](https://user-images.githubusercontent.com/10823148/66164207-feb4a080-e5e6-11e9-9d90-b083c50c383b.png)
![image](https://user-images.githubusercontent.com/10823148/66164216-04aa8180-e5e7-11e9-92d0-191b37c9a5dc.png)

**Comment by jinmingda** [comment]
It looks like the Picard module in MultiQC only responds to the key name `insert_smooth_points`. See [link](https://github.com/ewels/MultiQC/blob/f275ec9209ea4dd32cd2f2e62becd327fa866c44/multiqc/modules/picard/InsertSizeMetrics.py#L164). But in `assets/multiqc/multiqc_config.yaml`, it is actually `smooth_points`. https://github.com/nf-core/atacseq/blob/c2074b4b9717a312dcc49d81d4560c6588c95968/assets/multiqc/multiqc_config.yaml#L120. I haven't tested it but I was wondering if it would help if I change the key name from `smooth_points` to `insertsize_smooth_points`.

**Comment by jinmingda** [comment]
OK. I seem to fix the y value of the data points in insert size graph just by changing the plot ID to `picard_insert_size-1`. The ID in `multiqc_config.yaml` doesn't match the plot ID in the MultiQC report.

 https://github.com/nf-core/atacseq/blob/c2074b4b9717a312dcc49d81d4560c6588c95968/assets/multiqc/multiqc_config.yaml#L118.

**Comment by drpatelh** [comment]
Great. Thanks @jinmingda :+1: Ive been making some overdue changes to the pipeline over the last couple of days. If you spot anything else or have any other recommendations for the pipeline would be good to hear. Also, please feel free to join the atacseq channel on the nf-core Slack workspace:
https://nf-co.re/join

**Comment by jinmingda** [comment]
@drpatelh OK. I just started to process some samples with the pipeline. If I can confirm this is the right fix, I will create a PR later. Also, thank you for the invitation. I just joined the Slack group.

**Comment by drpatelh** [comment]
Cool. Yeah, as far as I can remember I added that snippet to the MultiQC config before it came out in the latest release, and then I forgot to test it! Good spot

**Comment by drpatelh** [comment]
Hi @jinmingda I cant seem to reproduce this error...I actually get `multiqc_report.html#picard-insertsize` when I click on the link in the MultiQC report. As far as I know you would only get `multiqc_report.html#picard-insertsize-1` if there were two insert size plots in the report.

Also, the plots in MultiQC and the original picard output file look similar enough in terms of the x-axis values (barring the smoothing of course).

Any ideas what may be going on here?

**Comment by drpatelh** [comment]
@jinmingda Going to close this for now. Reopen if and when required. Thanks!
