### ISSUE TITLE
Missing entries in Multiqc Report

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/atacseq#62]
I am missing a few samples here, which are listed in the General Statistics table. 
![Screenshot 2019-11-18 at 13 23 05](https://user-images.githubusercontent.com/12273093/69052190-af93c500-0a06-11ea-967f-aa500f9b36f7.png)

**Comment by drpatelh** [comment]
You should be able to pull down the plot using the bar underneath the x-axis labels?

**Comment by FriederikeHanssen** [comment]
Ah yes you are right, all samples are there. Didn't realise it could be enlarged there. Thanks!
