### ISSUE TITLE
Possibility for new Trim Galore using cutadapt 2 and mult-cores

### ISSUE THREAD

**Issue by drewjbeh** [nf-core/atacseq#63]
Hi there,

Firstly, thanks for a great tool. Really well packaged, and love the nextflow system so far. I only started using it yesterday and I already have great results - things are almost never this easy with bioinformatics tools, unfortunately.

I was wondering if it would be possible to include a newer version of Trim Galore. I have looked at change logs and it seems it would support cutadapt version 2.x which gives multi-core functionality for read trimming (using _-j_). This would substantially speed up the trimming step which can be a bit of a bottleneck. I personally have experience with cutadapt 2.x and the speed improvement is massive!

Thanks,
Drew

**Comment by drpatelh** [comment]
Hi @drewjbeh ! Thanks for the feedback and for giving the pipeline a test-drive. Glad you got some useful results out the other end :+1: 

I have updated all of the software for the next release. `TrinGalore` should now be the latest available on BioConda:
https://github.com/nf-core/atacseq/blob/04d24ed49f0502ee2458d8c063d5ccbbac4bea15/environment.yml#L25

I'm assuming that should also be using the latest version of `cutadapt`. I agree it would be really nice to use multiple cores. Its unacceptably slow. I was hoping to look into adding alternatives or to speed up this step at some point. I'm currently on paternity leave but you could create a PR to `dev` with the appropriate changes to the `TrimGalore` process. Could test these beforehand on your fork too. If not, I'm happy to look into this when I get back into work.

**Comment by drpatelh** [comment]
I can confirm that the latest version of `cutadapt=2.6=py37h516909a_0` is installed in the `dev` containers too so it should just be a case of testing the `TrimGalore` process with the additional parameters specifying the number of cores.

**Comment by drewjbeh** [comment]
Hi,

Thanks for the help. 
So I updated the `TrimGalore` process with the `-j $task.cpus` parameter but it is still using only one core according to the process log. I also made sure to add `pigz` to the environment file (see https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md under Full List of Options for Trim galore! `-j` section). 

I'm not really familiar with nextflow so could be missing something obvious, but other multi-core processes such as BWA and FastQC seem to use the `$task.cpus` flag to pass the user-defined core number to the process. I added it for both the single end and paired-end  options of the process so it looks something like this.
`
if (params.single_end) {
            """
            [ ! -f  ${name}.fastq.gz ] && ln -s $reads ${name}.fastq.gz
            trim_galore -j $task.cpus --fastqc --gzip $c_r1 $tpc_r1 $nextseq ${name}.fastq.gz
            """
        } else {
            """
            [ ! -f  ${name}_1.fastq.gz ] && ln -s ${reads[0]} ${name}_1.fastq.gz
            [ ! -f  ${name}_2.fastq.gz ] && ln -s ${reads[1]} ${name}_2.fastq.gz
            trim_galore -j $task.cpus --paired --fastqc --gzip $c_r1 $c_r2 $tpc_r1 $tpc_r2 $nextseq ${name}_1.fastq.gz ${name}_2.fastq.gz
            """
        }
`

Any suggestions?

**Comment by drpatelh** [comment]
Great! Its because you need to change the `label` for that process in order to specify the relevant resource requirements. At the moment its set to use 1 `cpu`, 7 GB `memory` and `20h` time as defined in the file below:
https://github.com/nf-core/atacseq/blob/04d24ed49f0502ee2458d8c063d5ccbbac4bea15/conf/base.config#L39

Can you change the label below to `label 'process_high'`
https://github.com/nf-core/atacseq/blob/04d24ed49f0502ee2458d8c063d5ccbbac4bea15/main.nf#L529

So it seems `pigz=2.3.4=0` gets installed automatically using the existing definitions in the environment, however, there is probably no harm in adding it explicitly if its a requirement.

**Comment by drpatelh** [comment]
Is there a bottleneck in terms of number of CPUs for `cutadapt`? i.e. a point where using additional CPUs compromises I/O or doesnt improve speed?

**Comment by drewjbeh** [comment]
Ahh makes sense, thanks!

RE your question about cutadapt and maximum cores, actually, yes. According to the link above:

> Actual core usage: It should be mentioned that the actual number of cores used is a little convoluted. Assuming that Python 3 is used and pigz is installed, --cores 2 would use 2 cores to read the input (probably not at a high usage though), 2 cores to write to the output (at moderately high usage), and 2 cores for Cutadapt itself + 2 additional cores for Cutadapt (not sure what they are used for) + 1 core for Trim Galore itself. So this can be up to 9 cores, even though most of them won't be used at 100% for most of the time. Paired-end processing uses twice as many cores for the validation (= writing out) step. --cores 4 would then be: 4 (read) + 4 (write) + 4 (Cutadapt) + 2 (extra Cutadapt) + 1 (Trim Galore) = 15, and so forth.
> 
> It seems that --cores 4 could be a sweet spot, anything above has diminishing returns.

Also, with the updated label, TrimGalore outputs the following in the log:
`Using an excessive number of cores has a diminishing return! It is recommended not to exceed 8 cores per trimming process (you asked for 12 cores). Please consider re-specifying`

Good news is that trimming is now lightning fast. Unfortunately I am getting the following error using the `dev` branch:
```
Error executing process > 'MakeGenomeFilter (genome.fa)'

Caused by:
  Process `MakeGenomeFilter (genome.fa)` terminated with an error exit status (1)

Command executed:

  samtools faidx genome.fa
  get_autosomes.py genome.fa.fai genome.fa.autosomes.txt
  cut -f 1,2 genome.fa.fai > genome.fa.sizes
  sortBed -i GRCm38-blacklist.bed -g genome.fa.sizes | complementBed -i stdin -g genome.fa.sizes | awk '$1 !~ /MT/ {print $0}' > genome.fa.include_regions.bed

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Chromosome "6" undefined in genome.fa.sizes

Work dir:
  /data/analysis/20191115_ATACseq/nfcore_atac/mouse_nfcoreEdit/work/50/2604aae73c350a900782dd27dea0d1

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

Something about chromosome 6 not being in the genome.fa.sizes file. This is using the GRCm38 reference. I can confirm that on the same data I do not get this error with the production version.

**Comment by drpatelh** [comment]
Ok. Lets change the `label` to `label 'process_medium'` instead. That will give 6 `cpus` but not far off the recommended 4 so it should be fine.

No idea where that error is coming from...assuming you havent changed anything else in the pipeline?

Can you run the below and see if it gives you any output:
`grep "6" /data/analysis/20191115_ATACseq/nfcore_atac/mouse_nfcoreEdit/work/50/2604aae73c350a900782dd27dea0d1/genome.fa.sizes`

**Comment by drewjbeh** [comment]
I don't believe I changed anything. To be sure I recloned the repo, made the changes and ran again. Same error.

The grep only finds chromosome 16 but no 6:
```
10	130694993
13	120421639
15	104043685
16	98207768
18	90702639
19	61431566
3	160039680
4	156508116
5	117594679
```

**Comment by drpatelh** [comment]
Can you run the command below:
`grep "6" /data/analysis/20191115_ATACseq/nfcore_atac/mouse_nfcoreEdit/work/50/2604aae73c350a900782dd27dea0d1/genome.fa.fai`

Im hoping its a faulty download of the reference in which case you could just run the pipeline again in a new directory.

**Comment by drpatelh** [comment]
Or if you want to run in the same directory do this first:
`rm -r results/ work/ .nextflow*`

**Comment by drewjbeh** [comment]
Ah yes, was a faulty genome.

Seems to be working now. I will make a PR for the changes.

**Comment by drewjbeh** [comment]
time reduced from over an hour to 18 minutes for the same data (56 million paired end reads)

**Comment by drpatelh** [comment]
Amazing! Thanks @drewjbeh . Ive sent you an invite to become a contributor to `nf-core` 👍 

Would be good if you can add your Institute and other details here using the instructions in the comment below:
https://github.com/nf-core/nf-co.re/issues/3#issuecomment-552184088

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/atacseq/pull/65
