### ISSUE TITLE
MergedLibBigWig chromosome length set incorrectly

### ISSUE THREAD

**Issue by RoganGrant** [nf-core/atacseq#68]
I'm currently reanalyzing the dataset found [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE116147), using the inbuilt GRCm38 genome. All works well up until the MergedLibBigWig step, which yields this error for all samples: 

> End coordinate 113762045 bigger than 9 size of 113761999 line 15030481 of Embryonic_day_16.5_R1.mLb.clN.bedGraph   
   
It seems that the size of chr9 is being set incorrectly? I guess I could try a hard-copy of mm10.

Full error message:

> Error executing process > 'MergedLibBigWig (Embryonic_day_16.5_R1)'
> 
> Caused by:
>   Process `MergedLibBigWig (Embryonic_day_16.5_R1)` terminated with an error exit status (255)
> 
> Command executed:
> 
>   SCALE_FACTOR=$(grep 'mapped (' Embryonic_day_16.5_R1.mLb.clN.sorted.bam.flagstat | awk '{print 1000000/$1}')
>   echo $SCALE_FACTOR > Embryonic_day_16.5_R1.mLb.clN.scale_factor.txt
>   genomeCoverageBed -ibam Embryonic_day_16.5_R1.mLb.clN.sorted.bam -bg -scale $SCALE_FACTOR -pc  | sort -k1,1 -k2,2n >  Embryonic_day_16.5_R1.mLb.clN.bedGraph
>   
>   bedGraphToBigWig Embryonic_day_16.5_R1.mLb.clN.bedGraph genome.fa.sizes Embryonic_day_16.5_R1.mLb.clN.bigWig
>   
>   find * -type f -name "*.bigWig" -exec echo -e "bwa/mergedLibrary/bigwig/"{}"\t0,0,178" \; > Embryonic_day_16.5_R1.mLb.clN.bigWig.igv.txt
> 
> Command exit status:
>   255
> 
> Command output:
>   (empty)
> 
> Command error:
>   End coordinate 113762045 bigger than 9 size of 113761999 line 15030481 of Embryonic_day_16.5_R1.mLb.clN.bedGraph
> 
> Work dir:
>   /projects/b1042/MorimotoLab/chaperome_development/heavner_bioRxiv_2019/ATAC-seq/work/39/6d4a6a35622f129913ad37255de539
> 
> Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by drpatelh** [comment]
Thanks @RoganGrant . Hmm. Im hoping it isnt an issue with the download of the genome. I am trying to reproduce the error locally by downloading the data. Can you send me the `design.csv` you are using, the command, and any custom config files please?

**Comment by RoganGrant** [comment]
Thanks for getting back so quickly! I have had issues with igenomes in other nf-core pipelines on my HPC, so it's possible there are issues on my end. 

Design is attached. Two things to note: 1) I used absolute paths just to be safe on the HPC, so these will need to be modified 2) I only pulled the samples listed (others are RNA-seq). I'll share the (hacky) R code I used to select:

```
library(GEOquery)
library(SRAdb)
srafile = getSRAdbFile()
con = dbConnect(RSQLite::SQLite(),srafile)

heavner_meta = Biobase::pData(phenoData(getGEO("GSE116147")[[1]]))
heavner_meta$srx = substring(as.character(heavner_meta$relation.1), 
                          regexpr("SRX", as.character(heavner_meta$relation.1)))
heavner_meta_atac = subset(heavner_meta, library_strategy == "ATAC-seq")
atac_files = listSRAfile(heavner_meta_atac$srx, con)
write.table(atac_files$run, 
            file = xxxxx
[191209_heavner_atac_metadata.txt](https://github.com/nf-core/atacseq/files/3956859/191209_heavner_atac_metadata.txt)
[191209_heavner_atac_metadata.txt](https://github.com/nf-core/atacseq/files/3956860/191209_heavner_atac_metadata.txt)

, 
            sep = "\n", row.names = F, quote = F, col.names = F)

#can then just feed this text file into fast[er]q-dump
```
Run command (had to resume after a timeout):
```
module load singularity
module load graphviz/2.40.1
nextflow run nf-core/atacseq \
-profile singularity \
-r 1.1.0 \
--input '191209_heavner_atac_metadata.csv' \
--genome GRCm38 \
--email xxxx \
--max_memory '100.GB' \
--max_time '47.h' \
--max_cpus 24 \
--min_reps_consensus 2 \
--email_on_fail \
--work-dir xxxx \
--outdir xxxx \
-resume
```
Nextflow config file:
```
process.executor = 'slurm'
process.queue = 'genomics'
process.clusterOptions = '-A b1042'
singularity.cacheDir = xxxx
```

**Comment by drpatelh** [comment]
Thanks! Ok, so the download is not going very well. Managed to download one `fastq` files from each sample which isnt really helpful 😅 Tried again but it keeps on dropping the connection...

You can download the `fastq` files directly using ['SRAExplorer'](https://ewels.github.io/sra-explorer/). Thats what I use for all public data downloads now. ts pretty cool. Having said that, you cant do anything if the servers arent behaving... 🙄 

`--work-dir` in the command is actually a Nextflow parameter so should be specified as `-work-dir` with a single-dash. This wont be why you are getting the error though. Everything else with the command, config and design looks good 👍 

Is the `genome.fa.sizes` file in the `work` directory for that process (`/projects/b1042/MorimotoLab/chaperome_development/heavner_bioRxiv_2019/ATAC-seq/work/39/6d4a6a35622f129913ad37255de539`) exactly the same as:

```
10      130694993
11      122082543
12      120129022
13      120421639
14      124902244
15      104043685
16      98207768
17      94987271
18      90702639
19      61431566
1       195471971
2       182113224
3       160039680
4       156508116
5       151834684
6       149736546
7       145441459
8       129401213
9       124595110
MT      16299
X       171031299
Y       91744698
```

If it is then it would be good if you can somehow zip and share the work directory with me so I can test it locally?

**Comment by RoganGrant** [comment]
I had forgotten about SRA explorer; thank you! Current workflow is a bit slow/indirect.

It looks like you've found the problem. I have a feeling the genome download was incomplete, as chr9 is truncated, and chrMT, chrX, and chrY are all absent:
```
10	130694993
11	122082543
12	120129022
13	120421639
14	124902244
15	104043685
16	98207768
17	94987271
18	90702639
19	61431566
1	195471971
2	182113224
3	160039680
4	156508116
5	151834684
6	149736546
7	145441459
8	129401213
9	113761999
```
I'm still happy to share the work directory, but probably no need unless you feel inclined. Should I just re-run from the top? Or try a hard-copy genome to be safe?
Also, would it be possible to have the pipeline check md5s or otherwise ensure downloads were successful?

Final thing: this levels of help is pretty rare on github. Thanks so much for your help!

**Comment by drpatelh** [comment]
Hi @RoganGrant . Youre very welcome :smiley_cat: 

Yep, no need to share the work directory. This problem with incomplete genome downloads has propped up a couple of times recently and it is slightly concerning. Luckily, `BEDTools` is fussed about the `genome.fa.sizes` file. This would have to be added as a core Nextflow feature though because the genomes are downloaded via staging using data in AWS `s3` buckets. I think we even created an issue there but I cant seem to find it now :thinking: 

If you will be working on mouse quite extensively I would actually recommend downloading the assembly directly from [AWS iGenomes](https://ewels.github.io/AWS-iGenomes/) and putting that somewhere central. This will then have all of the genome files required to run all relevant `nf-core` pipelines and you will only have to do this once. When running the pipeline, just add `--igenomes_base </PATH/TO/TOP_LEVEL/DIR>` to the command and it should work. The [`igenomes.config`](https://github.com/nf-core/atacseq/blob/master/conf/igenomes.config) will give you an idea as to what the directory structure should look like.

**Comment by c5creative** [comment]
Just FYI that we're also seeing incomplete downloads of the `GRCm38` genome.fa.
