### ISSUE TITLE
consensus_peaks.mLb.clN.boolean.intersect.plot.pdf not generated

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/atacseq#71]
[consensus_peaks.mLb.clN.boolean.intersect.txt.zip](https://github.com/nf-core/atacseq/files/4064086/consensus_peaks.mLb.clN.boolean.intersect.txt.zip)

When running the pipeline with a large number of samples (here: 88), the file ```consensus_peaks.mLb.clN.boolean.intersect.plot.pdf``` has ```0``` bytes in process ```MergedLibConsensusPeakSet```. Commenting out this [line](https://github.com/nf-core/atacseq/blob/fa1e3f8993cd20e249b9df09d29c5498eff311d2/main.nf#L1217) should circumvent the issue for now.

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/atacseq/pull/84
