### ISSUE TITLE
Add ataqv

### ISSUE THREAD

**Issue by ewels** [nf-core/atacseq#9]
Would be great to add ataqv! https://parkerlab.github.io/ataqv/

**Comment by drpatelh** [comment]
Agreed, it does have some very useful metrics. I did think about adding it to the pipeline but I think it only takes a single BAM as input which would mean merging all of the samples in a given experiment together. This could turn out to be massive, especially if you are doing footprinting. Not ideal... Having said that it shouldnt be too much work, and I could include a flag to be able to skip it.

**Comment by drpatelh** [comment]
I think it becomes more useful when you look at the results across the entire experiment because the plots are aggregated:
https://parkerlab.github.io/ataqv/demo/

Fancy writing a multiqc plugin? :tada:

**Comment by ewels** [comment]
Are you sure you need to merge multiple BAMs for that? That seems like it makes no sense..

**Comment by drpatelh** [comment]
I'll have a proper look. I haven't actually run it but someone else in the group has, and this is what he told me. That's why I didn't really bother with it for now.

**Comment by ewels** [comment]
I think you run it once per BAM file and it generates one JSON file per BAM then run `mkarv` on all of those JSON files to make the shared report.. So it should be two new processes and work very much like the MultiQC setup.

I spoke to the author at ASHG and asked about a MultiQC plugin. It would be nice to add, as then we can have these metrics alongside the others from the pipeline. It should be a pretty easy one to add as JSON format is super easy to parse and I think that most of the conventions are good. Could be a good first module perhaps @drpatelh...? 😉

**Comment by drpatelh** [comment]
Sweet. Ill try and add it in when I get a moment.

@drpatelh who?

**Comment by ewels** [comment]
Could be a good first bioconda package too 😆

**Comment by drpatelh** [comment]
BOOM!

https://github.com/bioconda/bioconda-recipes/tree/master/recipes/ataqv

Thanks for merging @apeltzer . What is the process now i.e. when does the package actually become available to `conda` after merging to master? This is what it says in the docs:
*When the PR is merged with the master branch, Circle CI will again do the builds but at the end will upload the packages to anaconda.org. Once this completes, and as long as the channels are set up as described in 2. Set up channels,*

**Comment by apeltzer** [comment]
Apparently there were some issues with uploading to Anaconda / bioconda (expired token by the bioconda team). This should be resolved, I'll ask in the bioconda channel.

**Comment by apeltzer** [comment]
OK I just asked them whats going on 👍

**Comment by drpatelh** [comment]
Thanks @apeltzer. I tried fishing around for the `master` CI section but couldnt find it. Ive joined the Gitter chat too.

Something looks fishy. Is the package being built under `Python 3.6`? I can see this in the CI output `ataqv-1.0.0-py36heba63b0_0.tar.bz2`. I have specified `Python 2.7` in `meta.yml`:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/ataqv/meta.yaml#L11

Not sure whats going on here...

**Comment by apeltzer** [comment]
Was just a little hickup of the uploader, its fine: https://bioconda.github.io/recipes/ataqv/README.html

**Comment by drpatelh** [comment]
https://github.com/bioconda/bioconda-recipes/pull/13160

**Comment by drpatelh** [comment]
https://github.com/bioconda/bioconda-recipes/pull/13374

**Comment by ewels** [comment]
![nice](https://typeset-beta.imgix.net/elite-daily/2016/06/16024428/tumblr_lrkn25ASca1qh9on4o1_500.gif)

**Comment by drpatelh** [comment]
Added in https://github.com/nf-core/atacseq/pull/16
