### ISSUE TITLE
 featurecounts_deseq2.r fails

### ISSUE THREAD

**Issue by mestia** [nf-core/atacseq#90]
While running atacseq pipeline we get the following error when it comes to MergedLibConsensusPeakSetDESeq 
`featurecounts_deseq2.r -i consensus_peaks.mLb.clN.featureCounts.txt -b '.mLb.clN.bam' -o ./ -p consensus_peaks.mLb.clN -s .mLb`

>  Warning messages:
>   1: package ‘S4Vectors’ was built under R version 3.4.4 
>   2: package ‘BiocGenerics’ was built under R version 3.4.4 
>   3: package ‘IRanges’ was built under R version 3.4.4 
>   4: package ‘GenomicRanges’ was built under R version 3.4.4 
>   5: package ‘GenomeInfoDb’ was built under R version 3.4.4 
>   6: package ‘SummarizedExperiment’ was built under R version 3.4.4 
>   7: package ‘Biobase’ was built under R version 3.4.4 
>   8: package ‘DelayedArray’ was built under R version 3.4.4 
>   9: package ‘matrixStats’ was built under R version 3.4.4 
>   converting counts to integer mode
>   estimating size factors
>   estimating dispersions
>   gene-wise dispersion estimates
>   mean-dispersion relationship
>   final dispersion estimates
>   fitting model and testing
>   Error in validObject(.Object) : 
>     invalid class “DESeqResults” object: superclass "list_OR_List" not defined in the environment of the object's class
>   Calls: results ... DESeqResults -> new -> initialize -> initialize -> validObject
>   Execution halted

Any hint is appreciated.
@ktrns, please feel free to provide more details.

**Comment by drpatelh** [comment]
Hi @mestia My suspicion is that this has something to do with a local installation of `R` conflicting with the version in the container. 

Please see the issue thread below and see if that solves the problem:
https://github.com/nf-core/tools/issues/541

Be interested to hear back. 

Have a great weekend!

**Comment by mestia** [comment]
Thanks for the hint, I'll check it. For now I run the dev singularity image with atacsec from dev branch and it successfully went through. Are there plans to release a new stable version any time soon?
Thanks!

**Comment by drpatelh** [comment]
No worries! Yep. I've already created a PR for the release:
https://github.com/nf-core/atacseq/pull/87

Need a couple of reviews and then should be ready to go. I'm planning on releasing it during the nf-core Hackathon next week but will try and close a couple of issues first. Hopefully soon :hourglass_flowing_sand:
