### ISSUE TITLE
DESeq2 dependency incompatibility

### ISSUE THREAD

**Issue by mashehu** [nf-core/atacseq#94]
When testing the fix for the `.Rprofile` problem, the empty file inside docker seems to have solved one issue, but now I get the following error message:
```
  Error: package ‘S4Vectors’ 0.22.1 was found, but >= 0.23.18 is required by ‘DESeq2’
  In addition: Warning message:
  version 0.24.0 of ‘S4Vectors’ masked by 0.22.1 in /crex/proj/uppstore2017255/private/matthias/Rpackages
  Execution halted
```

**Comment by drpatelh** [comment]
What exactly do you have in your `~/.Rprofile` @mashehu ? I have one too but Ive never seen these errors. Would like to try and reproduce locally if I can because I have no idea why we are still getting a clash there...

Im assuming you pulled the lastest `dev`container for the pipeline?

**Comment by drpatelh** [comment]
Ok. I tested this locally with the latest container and it appears the `~/Rprofile` actually resolves to the users home directory which leaves us no better than we were before 😅 

See https://github.com/nf-core/atacseq/pull/95

**Comment by mashehu** [comment]
I can't check, if commenting out my ~/.Rprofile (which contains a redirect of the libPaths), because now I got a new error weirder error:
```
Error executing process > 'BWAMem (OSMOTIC_STRESS_T0_R1_T1)'

Caused by:
  Unknown variable 'bwa_base' -- Make sure it is not misspelt and defined somewhere in the script before using it

Source block:
  prefix = "${name}.Lb"
  rg = "\'@RG\\tID:${name}\\tSM:${name.split('_')[0..-2].join('_')}\\tPL:ILLUMINA\\tLB:${name}\\tPU:1\'"
  if (params.seq_center) {
          rg = "\'@RG\\tID:${name}\\tSM:${name.split('_')[0..-2].join('_')}\\tPL:ILLUMINA\\tLB:${name}\\tPU:1\\tCN:${params.seq_center}\'"
      }
  """
      bwa mem \\
          -t $task.cpus \\
          -M \\
          -R $rg \\
          ${index}/${bwa_base} \\
          $reads \\
          | samtools view -@ $task.cpus -b -h -F 0x0100 -O BAM -o ${prefix}.bam -
      """
```

**Comment by mashehu** [comment]
Okay, the error seems to be fixed now.

**Comment by drpatelh** [comment]
Woooooohooooooo! Thanks alot @mashehu !
